version: '2'
services:
    mulubet-app:
        image: mulubet
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mulubet-mysql:3306/mulubet?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mulubet-mysql:
        extends:
            file: mysql.yml
            service: mulubet-mysql
